version: '3'
services:
  server:
    image: postgrest/postgrest
    container_name: rest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://authenticator:pangolinsecretpassword@db:5432/postgres
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pangolinsecretpassword
    volumes:
      - "/home/centos/data/all_pangolin_reworked.tsv:/tmp/all_pangolin_reworked.tsv"
      - "/home/centos/data/init.sql:/docker-entrypoint-initdb.d/init.sql"
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/centos/data/nginx:/etc/nginx/conf.d
      - /home/centos/data/certbot/conf:/etc/letsencrypt
      - /home/centos/data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - /home/centos/data/certbot/conf:/etc/letsencrypt
      - /home/centos/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
